<?php
// $Id:
/**
 * @file
 * The Doil module.
 */
function wdoil_link_alter(&$links, $node) {
  foreach ($links as $key => $value) {
    if (substr($key, 0, 14) == 'notifications_') {
      // Remove notificatinos links, so we can move them around
      unset ($links[$key]);
    }
  }
}

/**
 * Implementation of hook_block().
 */
function wdoil_block($op = 'list', $delta = 0) {
  global $user;
  if ($op == 'list') {
    $block[0]['info'] = t('doil - Hello visitor');
    $block[0]['cache'] = BLOCK_NO_CACHE;
    $block[1]['info'] = t('doil - facated-serach copy');
    return $block;
  }
  elseif ($op == 'view') {
    switch($delta) {
      case '0':
        $block['subject'] = '';
        // Add user image if it exists.
        if (!empty($user->picture)) {
          $picture = file_create_url($user->picture);
          $alt = t("@user's picture", array('@user' => $user->name));
          $user_picture = theme('image', $picture, $alt, $alt, '', FALSE);
          $block['subject'] .= '<span id="doil-hello-visitor-picture>"'. $user_picture .'</span>';
        }
                
        $block['subject'] .= t('Hello @visitor', array('@visitor' => !empty($user->uid) ? $user->name : t('visitor')));
        // Add links for anon or authenticated user.
        $user_links = $user->uid ? t('<a href="@user-profile">Edit profile</a>', array('@user-profile' => url('user/'. $user->uid. '/edit'))) : t('<a href="@login">Login</a> | <a href="@register">Register</a>', array('@login' => url('user'), '@register' => url('user/register')));
        $block['subject'] .= '<span id="doil-hello-visitor>"'. $user_links .'</span>';

        // Get the connected users. Taken from user module.
        $connected = module_invoke('user', 'block', 'view', 3);
        // Remove the 'online user' h3 tag.
        $block['content'] .= preg_replace('/\<h3(.*)h3\>/', '', $connected['content']);

        // Get newset user. Taken from user module.
        $sql = "SELECT uid, name FROM {users} WHERE status != 0 AND access != 0 ORDER BY created DESC";
        $result = db_fetch_object(db_query($sql));
        $block['content'] .= t('!user is that latest member in the site.', array('!user' => theme('username', $result)));
      break;
      case '1':
      $block['subject'] = '';
      $block['content'] = '';//drupal_get_form('doil_copy_facated_search');
    }
    return $block;
  }
}
/**
 * Implementation of hook_forms().
 */
function wdoil_forms($form_id) {
  $forms = array();
  if ($form_id =='doil_copy_facated_search') {
    $forms['doil_copy_facated_search']['callback'] = 'faceted_search_ui_form';
  }
  return $forms;
}
/**
 * Implementation of hook_form_FORMID_alter().
 */
function wdoil_form_doil_copy_facated_search_alter(&$form, $form_state) {
  $form['#submit'] = array('faceted_search_ui_form_submit');
}
